---
title: "Final Project - Reproducing a figure"
author: 
    name: "Monique Hernandez"
    email: mahernandez@ucsb.edu
    affiliation: 
    - University of California, Santa Barbara
    - Masters of Environmental Data Science, 2027
    - B.S. in Environmental Studies, 2025
date: "Augustt 28, 2026"
toc: true
format:
  html:
    theme: "pulse"
    other-links:
      - text: Course Website EDS 214 
        href: https://eds-214-reproducibility-m26.github.io/course-materials/final-project/final-project.html
      - text: Monique's website
        href: moniqueallyson.github.io
execute:
  message: false
  warning: false
---

# Background
Text can go here!

# Data

## Read in data
```{r, echo=FALSE}
library(tidyverse)
```

```{r, message=FALSE}

bq1 <- read_csv("../data/QuebradaCuenca1-Bisley.csv")
bq2 <- read_csv("../data/QuebradaCuenca2-Bisley.csv")
bq3 <- read_csv("../data/QuebradaCuenca3-Bisley.csv")
prm <- read_csv("../data/RioMameyesPuenteRoto.csv")
```

## Cleaning Data
```{r}

combined <- bind_rows(bq1, bq2, bq3, prm) # rbind won't be as effective as bind_rows

clean_combine <- combined |>
  select(Sample_ID, Sample_Date, `NH4-N`, `NO3-N`, Ca, Mg, K)

glimpse(clean_combine) # utilisizing glimpse in order to view the columns in the clean data
```

## Creating the tibble
```{r, message=FALSE}
combine_tibble <- tibble(
  window_start = seq(
    ymd("1988-01-05"),
    ymd("1994-12-31"),
    by = "9 weeks"
  ),
  site = NA,
  NH4N_ugl = NA,
  NO3N_ugl = NA,
  Ca_mgl = NA,
  Mg_mgl = NA,
  K_mgl = NA
)
```

## Calculating a moving average

```{r, message=FALSE}
w2 <- clean_combine$Sample_Date[1]
for (i in 1:nrow(combine_tibble)) {
  w1 <- w2
  print(w1)
  w2 <- w1 + weeks(9)
  print(w2)
  print('')
  k <- clean_combine$K[
    clean_combine$Sample_Date >= w1 & clean_combine$Sample_Date < w2
  ]
  mean_k <- mean(k, na.rm = TRUE)
  combine_tibble$K_mgl[i] <- mean_k
  mg <- clean_combine$Mg[
    clean_combine$Sample_Date >= w1 & clean_combine$Sample_Date < w2
  ]
  mean_mg <- mean(mg, na.rm = TRUE)
  combine_tibble$Mg_mgl[i] <- mean_mg
  nh4n <- clean_combine$`NH4-N`[
    clean_combine$Sample_Date >= w1 & clean_combine$Sample_Date < w2
  ]
  mean_nh4n <- mean(nh4n, na.rm = TRUE)
  combine_tibble$NH4N_ugl[i] <- mean_nh4n
  ca <- clean_combine$Ca[
    clean_combine$Sample_Date >= w1 & clean_combine$Sample_Date < w2
  ]
  mean_ca <- mean(ca, na.rm = TRUE)
  combine_tibble$Ca_mgl <- mean_ca
  no3n <- clean_combine$`NO3-N`[
    clean_combine$Sample_Date >= w1 & clean_combine$Sample_Date < w2
  ]
  mean_no3n <- mean(no3n, na.rm = TRUE)
  combine_tibble$NO3N_ugl <- mean_no3n
}
print(combine_tibble)
```


## Pivot long
```{r}
clean_combine_long <- combine_tibble |> #
  pivot_longer(
    # collapse columns in order to plot by ions & their concentration levels
    cols = !window_start & !site, # columns will NOT select with "!"
    names_to = "ion", # to have the ion listed
    values_to = "concentration" # for the columns need values from the ion concentrations
  )
print(clean_combine_long)
```

## Plot it!
```{r}

# Need sites lines
# Scale bny years
# scale by measurements

ggplot(
  data = clean_combine_long,
  mapping = aes(
    x = window_start,
    y = concentration,
    color = ion
  )
) +
  ggtitle(
    "Concentrations in Bisley, Puerto Rico streams before and after Hurricane Hugo, 9-wk moving
  averages"
  ) +
  geom_line() +
  geom_point() +
  labs(
    x = "Years",
    y = NULL
  ) +
  facet_wrap(~ion, scales = "free")
```

# Methods
Text can go here!

# Results
Text can go here!